### ISSUE TITLE
Do not use `eval()` in taking in user input

### ISSUE THREAD

**Issue by KotonBads** [adi-codess/Calculator#2]
https://github.com/adi-codess/Calculator/blob/bf2de040e4ca71cd1815431658328ebe38ada532/CLC.py#L2
![image](https://github.com/adi-codess/Calculator/assets/66117568/ade17bfc-d4f0-4375-96f9-dda995a035d4)

You're allowing the user to execute arbitrary Python code using `eval()`. Use `int()` or `float()` for a numerical value.

**Comment by adi-codess** [comment]
**Fixed !**
